let Favoritenumber=1
let petern="•\t\t\t\t\t\t\t\t\t\t\t\t\t\t•";
console.log("\n\n\n•••••••••••••••••••••••••••••••••••••••••••••••••Exercise 09•••••••••••••••••••••••••••••••••••••••••••••••••••••");
console.log(petern);
console.log(petern);
console.log(petern);
console.log(petern);
console.log(petern);
console.log("•","\t\t\t\t\t My Favorite Number is",Favoritenumber,"\t\t\t\t\t\t•");
console.log(petern);
console.log(petern);
console.log(petern);
console.log(petern);
console.log(petern);
console.log(petern);
console.log(petern);
console.log(petern);
console.log(petern);
console.log(petern);
console.log(petern);
console.log("•••••••••••••••••••••••••••••••••This program is created by Maqsood Ahmed••••••••••••••••••••••••••••••••••••••••\n");