console.log("•••••••••••••••••••••••••••••••••••••••••••••••••Exercise 00•••••••••••••••••••••••••••••••••••••••••••••••••••••");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                 Hello World                                                   •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•••••••••••••••••••••••••••••••••This program is created by Maqsood Ahmed••••••••••••••••••••••••••••••••••••••••");
