let pname1="maqsood ahmed";
console.log("•••••••••••••••••••••••••••••••••••••••••••••••••Exercise 03•••••••••••••••••••••••••••••••••••••••••••••••••••••");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                              My name is Upper Case :",pname1.toUpperCase(),"                                           •");
console.log("•                                                                                                               •");
console.log("•                              My name is Lower Case :",pname1.toLowerCase(),"                                           •");
console.log("•                                                                                                               •");
console.log("•                              My name is Title Case :",pname1.replace(/\b\w/g, (char) => char.toUpperCase()),"                                           •");
// console.log(pname1.replace(/\b\w/g, (char) => char.toUpperCase()));
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•••••••••••••••••••••••••••••••••This program is created by Maqsood Ahmed••••••••••••••••••••••••••••••••••••••••");
