let pname = "Maqsood Ahmed";
console.log("•••••••••••••••••••••••••••••••••••••••••••••••••Exercise 02•••••••••••••••••••••••••••••••••••••••••••••••••••••");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                              Hello", pname, ",would you like to learn some Python today?                  •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•••••••••••••••••••••••••••••••••This program is created by Maqsood Ahmed••••••••••••••••••••••••••••••••••••••••");
export {};
