console.log("•••••••••••••••••••••••••••••••••••••••••••••••••Exercise 04•••••••••••••••••••••••••••••••••••••••••••••••••••••");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•    Ali Ibn Abi Talib (R.A) once said,\“The richest of the rich is the one who is not a prisoner to greed.\”     •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•                                                                                                               •");
console.log("•••••••••••••••••••••••••••••••••This program is created by Maqsood Ahmed••••••••••••••••••••••••••••••••••••••••");
export {};
